# Generated by Django 2.0.5 on 2019-10-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Findings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
    ]
