# Generated by Django 2.0.5 on 2019-11-03 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('migrationcsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findings',
            name='author',
            field=models.TextField(default='Swapnil Deshmukh'),
        ),
        migrations.AddField(
            model_name='findings',
            name='date_last_edited',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='findings',
            name='reviwed_by',
            field=models.TextField(default='Swapnil Deshmukh'),
        ),
        migrations.AddField(
            model_name='findings',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
