# Generated by Django 2.0.5 on 2019-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationcsv', '0002_auto_20191103_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvssScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_base_score', models.CharField(max_length=200)),
                ('attack_vector', models.CharField(choices=[('N', 'Network'), ('A', 'Adjacent'), ('P', 'Physical'), ('L', 'Local')], default='N', max_length=1)),
                ('scope', models.BooleanField()),
                ('attack_complexity', models.BooleanField()),
                ('confidentiality', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default='N', max_length=1)),
                ('integrity', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default='N', max_length=1)),
                ('avaiability', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default='N', max_length=1)),
                ('privileges_required', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default='N', max_length=1)),
                ('user_instaction', models.BooleanField()),
            ],
        ),
    ]
