# Generated by Django 3.0.4 on 2020-03-12 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationcsv', '0003_cvssscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findings',
            name='date_last_edited',
            field=models.DateField(default=datetime.date(2020, 3, 12)),
        ),
    ]
