# Generated by Django 3.0.4 on 2020-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationcsv', '0004_auto_20200312_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findings',
            name='date_last_edited',
            field=models.DateField(auto_now_add=True),
        ),
    ]
