# Generated by Django 2.0.5 on 2019-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordvault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordvault',
            name='integer_value',
            field=models.IntegerField(default=10),
        ),
    ]
